---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namerd
  namespace: infra
spec:
  replicas: {{ .Values.namerd.replicas }}
  selector:
    matchLabels:
      app: namerd
  template:
    metadata:
{{- if .Values.namerd.podAnnotations }}
      annotations:
{{ toYaml .Values.namerd.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: namerd
    spec:
      dnsPolicy: ClusterFirst
      volumes:
      - name: namerd-config
        configMap:
          name: namerd-config
      containers:
      - name: namerd
        image: {{ .Values.namerd.image.repo }}:{{ .Values.namerd.image.tag }}
        imagePullPolicy: {{ .Values.namerd.image.pullPolicy }}
        command:
        - "taskset"
        - "--cpu-list"
        - "0"
        - "./bundle-exec"
        - "/io.buoyant/namerd/config/config.yml"
        - "-log.level=INFO"
        ports:
        - name: thrift
          containerPort: 4100
        - name: http
          containerPort: 4180
        - name: mesh
          containerPort: 4321
        - name: admin
          containerPort: 9991
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: "/admin"
            port: 9991
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: "namerd-config"
          mountPath: "/io.buoyant/namerd/config"
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.14.3
        args:
        - "proxy"
        - "-p"
        - "8001"
        resources:
          limits:
            memory: "20Mi"
          requests:
            memory: "20Mi"
